### ISSUE TITLE
Gripper Moveo Problem

### ISSUE THREAD

**Issue by Tonivalle** [jesseweisberg/moveo_ros#17]
Hello,
I am having a problem with the gripper in MoveIt. one of the grippers rods doesnt move and causes a collision. Attached is a recording of the problem.
My computer runs the latest ROS version on Ubuntu 16.04.
Thank you for your time.
[video.zip](https://github.com/jesseweisberg/moveo_ros/files/2857259/video.zip)

**Comment by jesseweisberg** [comment]
From the video, the first issue looks like you have a 'fixed' joint instead of 'revolute' or 'continuous' between the gripper gear link and the gripper tip link.  I'm not quite sure how this would happen unless you have changed the joint type in the URDF.
