### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by wheemzy1** [jesseweisberg/moveo_ros#3]
Hi Jesse,

Thanks for contributing this. I'm just getting familiar with ROS. After I installed Moveit and placed the package files in my catkin_workspace/src I then attempted to build using catkin_make. I received this error. 
......
[ 90%] Linking CXX executable /home/matthew/moveo_ws/devel/lib/moveo_moveit/moveit_convert
[ 90%] Built target moveit_convert
/home/matthew/moveo_ws/src/moveo_ros-master/moveo_moveit/src/move_group_interface_coor_1.cpp: In function ‘int main(int, char**)’:
/home/matthew/moveo_ws/src/moveo_ros-master/moveo_moveit/src/move_group_interface_coor_1.cpp:126:41: error: cannot convert ‘moveit::planning_interface::MoveItErrorCode’ to ‘bool’ in initialization
   bool success = move_group.plan(my_plan);
                                         ^
moveo_ros-master/moveo_moveit/CMakeFiles/move_group_1.dir/build.make:62: recipe for target 'moveo_ros-master/moveo_moveit/CMakeFiles/move_group_1.dir/src/move_group_interface_coor_1.cpp.o' failed
make[2]: *** [moveo_ros-master/moveo_moveit/CMakeFiles/move_group_1.dir/src/move_group_interface_coor_1.cpp.o] Error 1
CMakeFiles/Makefile2:2806: recipe for target 'moveo_ros-master/moveo_moveit/CMakeFiles/move_group_1.dir/all' failed
make[1]: *** [moveo_ros-master/moveo_moveit/CMakeFiles/move_group_1.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

I tried to troubleshoot and the closest I could find is this:  

https://github.com/ros-planning/moveit/commit/4033e577b64ab7ef0e4473342168494f69ef9324#diff-c41191af5080252e849ad41db505eac3

I tried modifying the first file listed, but could not locate the 2nd and 3rd files in order to modify. 
When I ran again, I still received an error. 

Please help.

**Comment by nez** [comment]
Hi @wheemzy1, I tried the following and now I'm being able to build:

on moveo_moveit/src/move_group_interface_coor_1.cpp on line 126:
remove:
```bool success = move_group.plan(my_plan);

ROS_INFO_NAMED("moveo", "Visualizing plan 1 (pose goal) %s", success ? "" : "FAILED");```

and replace with:
```move_group.plan(my_plan);```

I tried this, because move_group.plan returns apparently a MoveItErrorCode instead of boolean. (I don't know yet how to catch the status code correctly)

**Comment by wheemzy1** [comment]
thanks Nez, that solved it

**Comment by wheemzy1** [comment]
https://github.com/ros-planning/moveit/issues/759

**Comment by nez** [comment]
Hi @wheemzy1 great, so we can implement the solution offered by @BryceStevenWilley are you gonna make the PR? Otherwise I will :)

**Comment by wheemzy1** [comment]
go for it bud.
