### ISSUE TITLE
[ERROR] [1679484221.952115]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino

### ISSUE THREAD

**Issue by anand-010** [jesseweisberg/moveo_ros#42]
Running on ubuntu 18.04 ros melodic.
```
rosrun rosserial_python serial_node.py /dev/ttyACM0
[INFO] [1679484144.807291]: ROS Serial Python Node
[INFO] [1679484144.814112]: Connecting to /dev/ttyACM0 at 57600 baud
[INFO] [1679484146.922112]: Requesting topics...
[ERROR] [1679484161.925963]: Unable to sync with device; possible link problem or link software version mismatch such as hydro rosserial_python with groovy Arduino
```
this message repetes again and again.

**Comment by anand-010** [comment]
any one what is the right version of ros_serial works with this repo?.

**Comment by CKocher** [comment]
Hi, I know that it's been almost a year but did you find a solution to this problem? Any help would be highly appreciated! 

Best regards,

CK

**Comment by CKocher** [comment]
So all you did was changing the ros_serial versions?

**Comment by CKocher** [comment]
For anyone running into the same problem in the future:

Don't use the Arduino Moveo Software thats provided by BCN3D in the Repo that contains the STLs. There is another piece of Arduino software inside this Repo in the "moveo_moveit" folder -> THAT is the one that you have to run on your Arduino to make it work with ROS.

Kinda obvious but I seem to be not the only one that missed it at first.
