### ISSUE TITLE
sketch upload, ArmJointState.h error

### ISSUE THREAD

**Issue by bjela** [jesseweisberg/moveo_ros#7]
As mentioned, compiling error occurs. 

Yet after several library resets and another shot on different machine i'm sure I do not understand the process. 
Please advise, not a ROS rockstar

**Comment by jesseweisberg** [comment]
Please give more information about your issue so I can try to help.

**Comment by jesseweisberg** [comment]
Perhaps [this previous issue thread](https://github.com/jesseweisberg/moveo_ros/issues/4) may shed some light on your current problem.

**Comment by Jeroenh89** [comment]
Hi Jesse,

Iam currently havingthe same problem. Iam running Ubuntu 16.04 with Kinetic. My moveo_ros file is in the src directory.  I have the Moveit package succesfully running and i can do some fancy plan and execute simulations. 

I have the Arduino - ros lib unpacked in the libraries directory of arduino. I can do some simple arduino blinking with the example programs. 

However, when compiling the moveo_moveit_arduino i get the same error. Cant locate the "moveo_moveit/Armjointstate.h." 

I've deleted the ros_lib directory and used the "  rosrun rosserial_arduino make_libraries.py .
" command in the arduino - libraries folder. However, it does not seem to generate the armjointstate.h file in the arduino ros_lib.

**Comment by Jeroenh89** [comment]
Hmm, the catkin_make file does generate the ArmJointState.h in the build folder. However, if i run the "rosrun rosserial_arduino make_libraries.py . "  the file is not added to the ros_lib.

**Comment by Jeroenh89** [comment]
found the problem! I was running the source setup.bash and the rosrun rosserial_arduino make libraries in two differtent terminals... #noobmistake 

Now it seems to work!

**Comment by bjela** [comment]
Sweed Jeebus, that worked for me as well
Thanks guys!

**Comment by bjela** [comment]
Might be worth noting that sketch should be loaded from the catkin folder

**Comment by advait0810** [comment]
Hello. I've tried everything mentioned here and other places. My setup.bash files in kinetic and devel have been sourced. Everything in the same terminal as well. But it's not working.

**Comment by advait0810** [comment]
@ghost , what do you meant exactly by "sketch should be loaded from the catkin folder"?

**Comment by rootrootdoul** [comment]
still not working
